# comment


bulk_script = "scripts/bulk/relax_bulk.py"
slab_script = "scripts/slab/relax_slab.py"
adsorbate_script = "scripts/adsorbate/relax_adsorbate.py"


#rule load_dft_settings:
#    # TODO actually write this, or determine once and for all that it's a waste of time
#    # Script to copy DFT settings from config into the python scripts
#    input:
#        "../config/config.yaml"
#    output:
#        bulk_script,
#        slab_script,
#        adsorbate_script,
#    shell:
#        "echo hello"

rule calc_bulk:
    # Rule to compute the bulk constant
    input:
        bulk_script
    output:
        "../results/bulk/espresso.pwo",
        "../results/bulk/bulk.pwo"
    conda:
        "envs/qe.yaml"
    shell:
        """
        mydir=$(pwd)
        mkdir -p ../results/bulk
        cp {input} ../results/bulk
        cp scripts/bulk/run_bulk.sh ../results/bulk
        cd ../results/bulk
        sbatch run_bulk.sh
        cd $mydir
        """

rule relax_slab:
    input:
        rules.calc_bulk.output[0],
        slab_script
    output:
        "../results/slab/espresso.pwo",
        "../results/slab/slab.pwo"
    conda:
        "envs/qe.yaml"
    shell:
        """
        mydir=$(pwd)
        mkdir -p ../results/slab
        cp {rules.calc_bulk.output[1]} ../results/slab
        cp {input[1]} ../results/slab
        cp scripts/slab/run_slab.sh ../results/slab
        cd ../results/slab
        sbatch run_slab.sh
        """

rule name_files:
    input:
        bulk_script
    run:
        print(input)
        print(rules.calc_bulk.output)


