import numpy as np
import os
import sys
from datetime import datetime


# takes in arguments: destination directory
this_dir = os.path.dirname(__file__)
if len(sys.argv) < 2:
    print("need to pass the destination directory into make_ads_height.py script")
dest_dir = sys.argv[1] 

base_py = os.path.join(this_dir, 'place_adsorbate.py')
job_file = os.path.join(dest_dir, 'run_qe_jobs.sh')
os.makedirs(dest_dir, exist_ok=True)

# make files to run CO2 relaxation
hmin = 0.5
hmax = 7.5
N = 15
heights = np.linspace(hmin, hmax, N)


lines = [f'# Autogenerated {datetime.now()} from {base_py}\n\n']
with open(base_py, 'r') as f:
    for line in f:
        lines.append(line)

# create copies of the python file
for i, height in enumerate(heights):
    run_dir = os.path.join(dest_dir, f'run{i}')
    os.makedirs(run_dir, exist_ok=True)
    fname = os.path.join(run_dir, 'calc.py')
    pattern = 'height = 1.0'
    with open(fname, 'w') as f:
        for line in lines:
            if pattern in line:
                f.write(line.replace(pattern, f'height = {height}'))
            else:
                f.write(line)

run_i_dir = os.path.abspath(os.path.join(dest_dir, 'run$SLURM_ARRAY_TASK_ID'))
# write the array job file
with open(job_file, 'w') as f:
    f.write('#!/bin/bash\n\n')
    f.write('#SBATCH --time=24:00:00\n')
    f.write('#SBATCH --job-name=ads_height\n')
    f.write('#SBATCH --mem=40Gb\n')
    f.write('#SBATCH --partition=short,west\n')
    f.write(f'#SBATCH --array=0-{N - 1}\n\n')
    f.write(f'cd {run_i_dir}\n')
    f.write(f'python calc.py\n')

